Root login plays nice with gem.

diff --git a/home/mhodges/local/sbin/user_bash_init b/home/mhodges/local/sbin/user_bash_init
--- a/home/mhodges/local/sbin/user_bash_init
+++ b/home/mhodges/local/sbin/user_bash_init
@@ -57,33 +57,25 @@ function gem_bash_init_Main()
     if [[ ${gem_os} == *"MINGW64"* || ${gem_os} == *"CYGWIN"* ]]; then
 
         export gem_fullpath_android=$(cygpath "c:\android")
-        export gem_fullpath_android_sdk=${gem_fullpath_android}/sdk-tools-windows-4333796
-        export gem_fullpath_android_sdk_platform_tools=${gem_fullpath_android_sdk}/platform-tools_r28.0.1-windows/platform-tools
-        export gem_fullpath_android_sdk_tools=${gem_fullpath_android_sdk}/tools
-        export ANDROID_SDK=${gem_fullpath_android_sdk}
+        if [[ -d ${gem_fullpath_android} ]]; then
+            export gem_fullpath_android_sdk=${gem_fullpath_android}/sdk-tools-windows-4333796
+            export gem_fullpath_android_sdk_platform_tools=${gem_fullpath_android_sdk}/platform-tools_r28.0.1-windows/platform-tools
+            export gem_fullpath_android_sdk_tools=${gem_fullpath_android_sdk}/tools
+            export ANDROID_SDK=${gem_fullpath_android_sdk}
+        fi
 
     elif [[ ${gem_os} == "Linux" ]]; then
 
         export gem_fullpath_android=${HOME}/Android
-        export gem_fullpath_android_sdk=${gem_fullpath_android}/Sdk
-        export gem_fullpath_android_sdk_platform_tools=${gem_fullpath_android_sdk}/platform-tools
-        export gem_fullpath_android_sdk_tools=${gem_fullpath_android_sdk}/tools
-        export ANDROID_SDK=${gem_fullpath_android_sdk}
+        if [[ -d ${gem_fullpath_android} ]]; then
+            export gem_fullpath_android_sdk=${gem_fullpath_android}/Sdk
+            export gem_fullpath_android_sdk_platform_tools=${gem_fullpath_android_sdk}/platform-tools
+            export gem_fullpath_android_sdk_tools=${gem_fullpath_android_sdk}/tools
+            export ANDROID_SDK=${gem_fullpath_android_sdk}
+        fi
 
     else
-		echo "ERROR: Build platform not supported: ${gem_os}"
-    fi
-
-    # Validate android sdk directories.
-    if [[ ! -d ${gem_fullpath_android_sdk} ]]; then
-        echo "$BASH_SOURCE(${LINENO}) WARNING: Android SDK directory does not exist: \${gem_fullpath_android_sdk}=${gem_fullpath_android_sdk}"
-    else
-        if [[ ! -d ${gem_fullpath_android_sdk_platform_tools} ]]; then
-            echo "$BASH_SOURCE(${LINENO}) WARNING: Android SDK platform tools directory does not exist: \${gem_fullpath_android_sdk_platform_tools}=$gem_fullpath_android_sdk_platform_tools}"
-        fi
-        if [[ ! -d ${gem_fullpath_android_sdk_tools} ]]; then
-            echo "$BASH_SOURCE(${LINENO}) WARNING:  Android SDK tools directory does not exist: \${gem_fullpath_android_sdk_tools}=$gem_fullpath_android_sdk_tools}"
-        fi
+		echo "ERROR: Build platform not supported: ${gem_os}" ; exit
     fi
     export PATH="${PATH}:${gem_fullpath_android_sdk_platform_tools}:${gem_fullpath_android_sdk_tools}"
 
@@ -100,11 +92,13 @@ function gem_bash_init_Main()
         fi
     elif [[ ${gem_os} == "Linux" ]]; then
 
-        which code &>/dev/null
-        if [[ $? -ne 0 ]]; then
-            echo "$BASH_SOURCE(${LINENO}) WARNING: Failed to find Visual Studio Code in directory: ${gem_fullpath_vscode}"
+        gem_fullpath_vscode=$(which code)
+        if [[ $? -ne 0 ]] || [[ ! -f ${gem_fullpath_vscode} ]]; then
+            echo "$BASH_SOURCE(${LINENO}) WARNING: Failed to find Visual Studio Code."
         fi
     fi
+    # Escape spaces.
+    gem_fullpath_vscode_exe=$(echo ${gem_fullpath_vscode} | sed 's/ /\\ /g')
 
 
     # =========================================================================
@@ -140,11 +134,7 @@ function gem_bash_init_Main()
     # Aliases
     # =========================================================================
     alias ls='ls -al --color=auto'
-    if [[ ${gem_os} == *"MINGW64"* || ${gem_os} == *"CYGWIN"* ]]; then
-        # Escape spaces.
-        gem_fullpath_vscode_exe=$(echo ${gem_fullpath_vscode} | sed 's/ /\\ /g')
-        alias code="${gem_fullpath_vscode_exe} --user-data-dir=${HOME}/.config/Code/"
-    fi
+    alias code="${gem_fullpath_vscode_exe} --user-data-dir=${HOME}/.config/Code/"
 
 
     # =========================================================================
@@ -158,7 +148,9 @@ function gem_bash_init_Main()
 
 
     # Where would you like to go today?
-    cd ~/gem/local/src
+    if [[ -d ${gem_fullpath_gem} ]]; then
+        cd ${gem_fullpath_gem}/local/src
+    fi
 }
 gem_bash_init_Main
 
